#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
# Configure uncomplicated firewall
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

# Start Nginx
/usr/sbin/nginx

