#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

# Create redirection file configuration
new_text="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ynot93\/ permanent;"

sudo sed -i "s/server_name _;/$new_text/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
