#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

# Create redirection file configuration
new_block = "server {
    listen 80;
    
    server_name _;

    location redirect_me {
        return 301 https://github.com/ynot93/;
    }

    # Additional server configuration
}"

sudo sed -i "/server_name _;/c\\$new_block" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
