#!/usr/bin/env bash 
# Configure load-balancer HAProxy to manage traffic between both servers

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_configuration=\
"
frontend tonymputhia.tech_frontend
        bind *:80
        default_backend tonymputhia.tech_backend
backend tonymputhia.tech_backend
        balance roundrobin
        server 476642-web-01 54.87.250.109:80 check
        server 476642-web-02 54.90.5.67:80 check
"
echo "$server_configuration" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
