#!/usr/bin/env bash
# Group visitors by IP and status codes from apache log using awk

log_file="apache-access.log"

if [ -e "$log_file" ]; then
    awk '{ print $1, $9 }' "$log_file" | sort | uniq -c | sort -nr
else
    echo "Error: $log_file does not exist."
fi
