#!/usr/bin/env bash
# Use while loop to print bad luck on 4th iteration,
# good luck on 8th iteration and Best school on the rest.

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
