#!/usr/bin/env bash
# Confugures IP addresses of servers

cp /etc/hosts ~/hosts.new
echo '8.8.8.8  facebook.com' >> ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
